; <?php die(); ?>
sourceDir = ""
destDir = ""
splDir = ""
cplDir = ""
plgDir = ""
masDir = ""
xmlDir = "1"
[directives]
PLUGIN_AUTOLOAD = "1"
CUSTOM_RESOURCES = "1"
DEBUG_CONSOLE = "1"
GZIP_SUPPORT = "1"
OUTPUT_CACHING = "1"
COMPONENTS = "1"
PREDEFINED_COMPONENTS = "1"
REGISTER_FAMILY = "1"
OBJECT_I18N = "1"
HTTP_HEADERS = "1"
DYNAMIC_SECTIONS = "1"
MASTER_TEMPLATES = "1"
PAGESYSTEM = "1"
